### ISSUE TITLE
colourInput() has been moved to the 'colourpicker' package

### ISSUE THREAD

**Issue by 0Isaiah** [ropenscilabs/eechidna#18]
```
library(eechidna)
launchApp()

```
Error: colourInput() has been moved to the 'colourpicker' package.
 
```
library(colourpicker)
 launchApp()

```
Error: colourInput() has been moved to the 'colourpicker' package.

**Comment by benmarwick** [comment]
I can see this message with the CRAN release, but not with the github release. Can you confirm that the github release works fine for you? Looks like we need to send another update to CRAN!

**Comment by 0Isaiah** [comment]
Thanks Ben, 1.2 works fine.
