### ISSUE TITLE
Cartogram dependency

### ISSUE THREAD

**Issue by cpsievert** [ropenscilabs/eechidna#2]
There was [some discussion](https://github.com/ropensci/auunconf/issues/20#issuecomment-214072089) between @dicook & @benmarwick on adding chxy/cartogram as a dependency.

Just FYI, if we want, we can use the `Remotes:` field ([like this](https://github.com/tdhock/animint/blob/b0a708d82b58a8ac266c70495500a1fb3dc2470b/DESCRIPTION#L33-L35)) to depend on github packages and we should still pass R CMD check (I think).

**Comment by benmarwick** [comment]
Thanks for the pointer, that looks straightforward. It doesn't seem to cause a problem with R CMD check, but I wonder if it will pass CRAN checks? Reading [here](https://cran.r-project.org/web/packages/devtools/vignettes/dependencies.html) I see:

> When you submit your package to CRAN, all of its dependencies must also be available on CRAN. For this reason, release() will warn you if you try to release a package with a Remotes field.

**Comment by cpsievert** [comment]
Ah, that makes sense, and good to know, thanks.
