### ISSUE TITLE
More control to plot?

### ISSUE THREAD

**Issue by ghost** [ropenscilabs/eechidna#20]
Hello all,

Thank you very much for the library, I think it is great and easy to use :)

Is it possible to add a bit more configuration to the plotting part? In particular I would like:
- Add a border
- Store the plot as a variable.

For now I'm using the eechidna:::dorling function to make Dorling Cratograms. (Maybe it is possible to do this already but I haven't found how to do it D:)

Cheers and thank you for your help,
Vanessa

**Comment by benmarwick** [comment]
Hello,

If your main goal is to make Dorling cartograms, it might be simplest to start with this pkg: https://github.com/chxy/cartogram by @chxy

Which plots are you referring to in your question? We have a lot in the vignettes and shiny app! Most can be customised further with regular ggplot or plotly code.

**Comment by ghost** [comment]
Hello Ben,

Thank you very much for your reply. I have tried the library you suggested but as I obtained better results with yours I decided to use it instead. I'll give it another try to chxy/cartogram.

The plot I was referring to is the one that is generated from using the `dorling` function from here: https://github.com/ropenscilabs/eechidna/blob/master/R/cartogram.R . If I understand correctly, that function creates and plot a Dorling Cartogram. I really like the results but I don't understand how to make it more customizable. I'm not using shiny app for now as I was generating simple Dorling cartograms.

Cheers and thank you,
Vanessa

**Comment by benmarwick** [comment]
Thanks for those further details. I think the output is a ggplot object, so you can customize further in the usual way that you work with ggplot output, e.g. `+ theme_minimal()` etc. 

If you could include here some code that is a small, self-contained example of what you are looking at, 
 or a link to your repo where your project is visible than perhaps I could give more specific suggestions.

**Comment by ghost** [comment]
Hi Ben,

Thank you for your reply and sorry for my late one. Here I attach a the basic code of what I'm trying to do:

```
# Load Libraries
library(eechidna)
library(cartogram) # chxy/cartogram
library(hrbrthemes)
library(tidyverse)
library(RColorBrewer)

filePath = 'data/'
filename = 'usstates_positive_increasing_100.csv'

# Load data & merge
data <- readr::read_csv(file=file.path(filePath, filename))
states_info <- as_tibble(state.carto.center)
states_info$State <- state.abb
data <- merge(data, states_info, by.x = 'Abbreviation', by.y='State')

# Remove Hawaii and Alaska
data <- subset(data, Abbreviation != 'HI')
data <- subset(data, Abbreviation != 'AK')

# Transform y for color bining
n_times <- 12
all_y = c()
for (time in 1:n_times){
    var_name <- paste('y_', time, sep = "")
    all_y <- c(all_y, data[[var_name]])
}
inter_size = (max(all_y)-min(all_y))/5
for (time in 1:n_times){
    var_color <- paste('y_', time, sep = '')
    data[[var_color]] <- sapply(data[[var_color]], cut, seq(min(all_y), max(all_y), inter_size), labels=1:5, include.lowest = TRUE)
}

# Create dorling cartogram
par(family=font_rc, col="black")
cols <- brewer.pal(5, "Blues")
var_area <- paste('x_', 10, sep = '')
var_color <- paste('y_', 10, sep = '')
p <- eechidna:::dorling(data$Abbreviation, data$x, data$y, data[[var_area]], iteration=100, name.text=TRUE, 
                            dist.ratio=1.2, xlab='', ylab='', col=cols[data[[var_color]]], frame=FALSE, asp=1,
                            family=font_rc, cex.main=1.75, adj=0, ggplot2=TRUE)
```
I also attach the csv file of the data (with .txt extension as Github doesn't allow .csv) and a image of the results I obtain now. The resulting object p is a list so when I try to do ``` + theme_minimal() ``` I get the following warning:

Warning message in eval(expr, envir, enclos):
“Incompatible methods ("Ops.data.frame", "+.gg") for "+"”

Best regards and thank you for your help,
Vanessa

[usstates_positive_increasing_100.txt](https://github.com/ropenscilabs/eechidna/files/2820861/usstates_positive_increasing_100.txt)
![screenshot from 2019-02-01 10-05-00](https://user-images.githubusercontent.com/582625/52113172-eaa84180-2608-11e9-901f-1311e77e8384.png)

**Comment by dicook** [comment]
Vanessa,

Xiaoyue, the author of the algorithm, may be able to help you - I’ve forwarded your message to her. 

cheers,
Di

**Comment by ghost** [comment]
Hi Dianne,

Thanks for your help.

Cheers,
Vanessa
