### ISSUE TITLE
Imputing electorates - Error when calling weighted_avg_census_sa1 

### ISSUE THREAD

**Issue by onrvam** [ropenscilabs/eechidna#24]
Hello, 

Firstly, thanks for creating this awesome package. It really makes working with electoral data and census data easy and enjoyable! 

I am planning to add some additional variables from the Census data to my data frames, which currently consist of eechidna abs and some variations of the aec variables. For the years when there was an election but no census, I have decided to follow the imputation strategy that you have introduced. Hence, I tested whether I can replicate the code on imputation vignette. I got an error message (Error: object 'CD' not found) after calling weighted_avg_census_sa1 on the mapping. See the code and error message below. I also got warnings after calling allocate_electorate, which I have attached below. I tried the weighted_avg_census_sa1 also with a data frame consisting of one additional variable from census data 2011, but I got the same error message as  I got with the abs2011 data. 

I'm currently using github installation of the package but got the same error message with r-cran version last week.

Thanks for help!
Onerva M.

##

Code below:

> # shapefile containing electoral boundaries from the 
> # 2013 federal election
> sF_13 <- sF_download(year=2013)
trying URL 'https://github.com/ropenscilabs/eechidna/raw/master/extra-data/sF_13.rda'
Content type 'application/octet-stream' length 306828 bytes (299 KB)
downloaded 299 KB
> data(abs2011)
> # load the centroids of 2011 SA1 polygons
> load("centroids_sa1_2011.rda")
> # allocate electorate to allocate each SA1
> # to the electoral boundary in which it sits
> mapping_c11_e13 <- allocate_electorate(centroids_ls = centroids_sa1_2011, electorates_sf = sF_13, census_year = "2011", election_year = "2013")
[1] 2000
[1] 4000
[1] 6000
[1] 8000
[1] 10000
[1] 12000
[1] 14000
[1] 16000
[1] 18000
[1] 20000
[1] 22000
[1] 24000
[1] 26000
[1] 28000
[1] 30000
[1] 32000
[1] 34000
[1] 36000
[1] 38000
[1] 40000
[1] 42000
[1] 44000
[1] 46000
[1] 48000
[1] 50000
[1] 52000
[1] 54000
There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
2: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
3: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
4: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
5: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
6: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
7: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
8: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
9: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
10: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
11: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
12: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
13: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
14: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
15: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
16: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
17: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
18: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
19: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
20: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
21: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
22: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
23: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
24: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
25: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
26: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
27: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
28: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
29: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
30: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
31: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
32: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
33: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
34: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
35: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
36: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
37: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
38: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
39: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
40: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
41: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
42: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
43: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
44: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
45: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
46: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
47: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
48: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
49: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
50: In RGEOSBinPredFunc(spgeom1, spgeom2, byid, func) :
  spgeom1 and spgeom2 have different proj4 strings
**> census_aec13_11 <- weighted_avg_census_sa1(mapping_df = mapping_c11_e13, abs_df = abs2011)
Error: object 'CD' not found**

**Comment by jforbes14** [comment]
Hi Onerva,

The issue here is using the function `weighted_avg_census_sa1`, which is designed for imputing using Census data aggregated at "SA1" level (also known as "Collection District"). The object `abs2011` is Census data aggregated at "Census Division" level, and should be used with the `weighted_avg_census` function. For reference, there are ~50,000 SA1s in Australia, and 150 CEDs, so SA1 is far more disaggregate. 

The SA1 dataframe for 2011 Census (`abs2011_cd`) can be found in the "data-raw/imputing-using-sa1" folder of this repo if you wanted to use that (for a more disaggregate imputation), and the corresponding script that created it is `abs2011-SA1.R`.

Best,
Jeremy
