### ISSUE TITLE
URL in GitHub Repo incorrect

### ISSUE THREAD

**Issue by bryceroney** [ropenscilabs/eechidna#29]
I noticed that the URL link on the GitHub repo returns a 404 error from ROpenSci.org, is that still the correct URL?

**Comment by danmackinlay** [comment]
AFAICT ropensci no longer endorses eechidna - it is not listed on the packages page - https://ropensci.org/packages/all/

**Comment by jforbes14** [comment]
Thanks for pointing this out @bryceroney. I now own the repo and links have been redirected to return the page associated with my account - see [here](https://jforbes14.github.io/eechidna/index.html)
