### ISSUE TITLE
Add another view to shiny app

### ISSUE THREAD

**Issue by cpsievert** [ropenscilabs/eechidna#3]
We have space for at least one more view in the top row of the shiny app (the same row as the map and the proportions by party). Any ideas on what we should show?

**Comment by NTomasetti** [comment]
Is there anywhere that has the actual elected party on the x axis? We have
votes but this might be useful too

**Comment by benmarwick** [comment]
Perhaps we could colour the name of the winning party in the x-axis labels, to make it stand out?

**Comment by cpsievert** [comment]
Added a bar chart in 84bcfb16d86a86c5298b5fd1dd37cf22d5bfe4f4 to show the number of electorates won by party. Next step is to make those bars selectable via click

**Comment by benmarwick** [comment]
Bar chart on the left looks great! I think I prefer the jittered points over the line plot that I currently see on the center plot. With the jittered points it's easier to inspect individual electorates. Plus I don't think we have a good justification for continuity or trends between different parties, in the way that the line plot implies (my impression was that line plots were suitable only for continuous variables on the y-axis, I'm not sure that have a strong case for that here with the political parties, which seem more discrete to me). So I think the jittered points are a better option here, as we had before, but I'm curious to hear what others think. Here are the two:

![clipboard02](https://cloud.githubusercontent.com/assets/1262179/15097099/88252554-153b-11e6-99bc-68766e01786a.png)

![clipboard03](https://cloud.githubusercontent.com/assets/1262179/15097176/7b4fb96e-153d-11e6-8548-fdadbab1cf05.png)

The stacked dot-plots below pose challenges for identifying the coloured dots, perhaps it just me on my small laptop screen. I wonder if we could also bump up the size of the points that change colour?

**Comment by cpsievert** [comment]
Thanks @benmarwick. The lines are there to make it easier to see the distribution of 1st preference voting for a given electorate. There are some types of visualizations, such as [parallel coordinates](https://en.wikipedia.org/wiki/Parallel_coordinates), that connect lines across a discrete axis. I do agree the lines make it harder to select electorates based on this plot, but I think this could be remedied by an increase in size of the points connected to each line (and, in fact, I think I'll try this as well as reducing the alpha chanell on the lines).

I strongly agree about the sizing of dots in the dot plot, but this a difficult problem. If we simply increase the size of the points, distribution modes will be cut off. I was able to avoid this a bit by focusing mostly on non-heavily-skewed distributions, but I'm starting to wonder if histograms would be a better alternative...

**Comment by dicook** [comment]
From the little black box...

I think the dotplot function in gglot2 is buggy. This is a pretty new function, and I hadnt tried it until Carson used it for this app. If you play with the aspect ratio of the plot you can get everything looking good, but its very tricky to make this work universally. The aspect ratio available in the app is also constrained by the other plots showing. @benmarwick @cpsiervert
