### ISSUE TITLE
2019 data

### ISSUE THREAD

**Issue by danmackinlay** [ropenscilabs/eechidna#30]
Over the summer holidays 'd like to pull in the [2019 election results to the project](https://results.aec.gov.au/24310/Website/HouseResultsMenu-24310.htm). Before I do so,  is there anything I should know about best practices for this? The format should, I suppose be much like the 2016 results.

**Comment by danmackinlay** [comment]
Perhaps @emitanaka specifically could let me know: are you or your students already doing this? I notice your fork has some updates

**Comment by emitanaka** [comment]
@danmackinlay I'm not working actively on it so feel free to ignore mine! I just needed a fix to the vic map since the original seemed to have issues but I don't have much time to do a proper test for my code addition, so I don't plan on pushing my changes any time soon.

**Comment by danmackinlay** [comment]
It looks like you did solid work though, will try to see if I have enough time to take it anywhere. We need another R unconf to get this done, eh?

**Comment by jforbes14** [comment]
@danmackinlay @emitanaka what specifically was the problem here? I'll try to resolve if I can get my head around it

**Comment by bryceroney** [comment]
Isn't the 2019 data already available in `fp19` and `tcp19`? Either way, happy to help where I can on the project.

**Comment by danmackinlay** [comment]
Yes the 2019 data is here! It is absent from several places in the documentation, but is in fact there, I discovered upon installation. Possible an imputed version of the ABS data might be wise also, but that is a separate question.

I did, however, notice that there is a glitch in the 2019 data. Specifically, the Greens party is missing the Greens Victoria, so I had to fix that before I could use the data. Here is what I mean: https://github.com/danmackinlay/eechidna/commit/0deeac67da27be7eeaaf08a2922282f9428ad59a

**Comment by danmackinlay** [comment]
Cripes I just noticed what a messy diff that is. Looks like it picked up some whitespace normalization when I did the rebase. Sorry!
Anyway, I can prepare a clean patch which preserves all the trailing whitespace if desired; the real change is only 2 lines.

**Comment by jforbes14** [comment]
Yes a patch would be great @danmackinlay! 
I'll also make some moves on the ABS imputation for 2019 👍

**Comment by bryceroney** [comment]
I'm happy to look over updating the documentation to make sure it's referenced correctly.

**Comment by danmackinlay** [comment]
Possibly a side issue, or a separate documentation ticket, but what is the canonical way to regenerate the package data after changing the import scripts? If I do what I assume the right thing is and source the script `data-raw/all-electorate-votes.R` from the package root it seems to do the right thing but it also throws some errors about missing names in the ABS tables.
Anyway, by that method I updated some data - see 
https://github.com/danmackinlay/eechidna/commit/624a58d0c3f650911861b7c6f742ea87a1b56eae

but I would like to know I'm not breaking anything before I make a new pull request with other similar updates.

**Comment by jforbes14** [comment]
@danmackinlay I've merged your PR and have updated the 2019 election data on master. I'm working on a new release for this, so the CRAN version will also be updated soon (also pending documentation review @bryceroney ).

Some of the wrangling scripts including `data-raw/all-electorate-votes.R` are a bit confusing because they are expecting objects mid-wrangle. Probably an exercise for me to go and do some refactoring.

**Comment by danmackinlay** [comment]
Should we close this issue in favour of openeing new tickets for new issues as they arise?
