### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by OmidGhasemi21** [ropenscilabs/eechidna#45]
Hi there,

I am following the instructions at (https://jforbes14.github.io/eechidna/index.html) to install the package but I have no success.

```r
install.packages("eechidna")
# Warning in install.packages :
#   package ‘eechidna’ is not available for this version of R
```

```r
devtools::install_github("jforbes14/eechidna", build_vignettes = TRUE)
# Using GitHub PAT from the git credential store.
# Downloading GitHub repo jforbes14/eechidna@HEAD
# Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
#   download from 'https://api.github.com/repos/jforbes14/eechidna/tarball/HEAD' failed
```

```r
> sessionInfo()
# R version 4.3.3 (2024-02-29)
# Platform: aarch64-apple-darwin20 (64-bit)
# Running under: macOS Ventura 13.0.1
```

I appreciate your help and assistance.

Thanks.
Omid

**Comment by njtierney** [comment]
Hi there,

I am able to install `eechidna` using the same instructions - I think there might be something going on with your internet connection - perhaps some Wifi permissions / firewall?

> download from 'https://api.github.com/repos/jforbes14/eechidna/tarball/HEAD' failed

Seems to indicate some issue with downloading the package - this SO thread might have some potential answers for you:

https://stackoverflow.com/questions/53845962/having-trouble-getting-devtoolsinstall-github-to-work-in-r-on-win-7-
64bit-ma

**Comment by OmidGhasemi21** [comment]
Brilliant. Thanks @njtierney for the help. I tried my mobile internet and it was a success.

I did not know that you are an author of eechidna. I am a big fan of your nanier package.

**Comment by njtierney** [comment]
Thanks! Glad to hear it worked and thanks for the kind words 😃
