### ISSUE TITLE
R CMD check

### ISSUE THREAD

**Issue by dicook** [ropenscilabs/eechidna#6]
Check the package build again, that example code delimited by \dontrun, might be made to run, in the package submission to CRAN.

**Comment by cpsievert** [comment]
We're now passing :)

**Comment by benmarwick** [comment]
I'm stuck on 'Package has a VignetteBuilder field but no prebuilt vignette index.' in the win build log. Any ideas?

```
* using log directory 'd:/RCompile/CRANguest/R-devel/eechidna.Rcheck'
* using R Under development (unstable) (2016-05-17 r70629)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'eechidna/DESCRIPTION' ... OK
* this is package 'eechidna' version '0.1'
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Ben Marwick <benmarwick@gmail.com>'

New submission

Package has a VignetteBuilder field but no prebuilt vignette index.
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'eechidna' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... [2s] OK
** running examples for arch 'x64' ... [2s] OK
* checking PDF version of manual ... OK
* DONE
Status: 1 NOTE
```

**Comment by cpsievert** [comment]
Did 1a304f3 not fix it?

**Comment by benmarwick** [comment]
Nope, I just pulled and did `devtools::build_win()` again, and got the same note about `Package has a VignetteBuilder field but no prebuilt vignette index.`

**Comment by njtierney** [comment]
can I suggest we add appveyor-CI to the package? This is basically a windows version of Travis. You can use `devtools::use_appveyor()` to do so. I can't right now as I changed my github username and appveyor has locked me out.

**Comment by benmarwick** [comment]
Thanks @njtierney, good idea! Done with 7065afb053e78fb64364e9a3073bc27bcbce87b7

**Comment by benmarwick** [comment]
@sckott do you have any thoughts about the `Package has a VignetteBuilder field but no prebuilt vignette index.` note?

**Comment by sckott** [comment]
👀 looking

**Comment by sckott** [comment]
possibility in above commit comment

**Comment by benmarwick** [comment]
No change when using `knitr::knitr` in the vignette header... @cpsievert we have some new `Codoc mismatches`  from your recent changes...

```
* using log directory 'd:/RCompile/CRANguest/R-devel/eechidna.Rcheck'
* using R Under development (unstable) (2016-05-18 r70631)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'eechidna/DESCRIPTION' ... OK
* this is package 'eechidna' version '0.1'
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Ben Marwick <benmarwick@gmail.com>'

New submission

Package has a VignetteBuilder field but no prebuilt vignette index.
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'eechidna' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... NOTE
Non-standard file/directory found at top level:
  'README.html'
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... WARNING
Codoc mismatches from documentation object 'launchApp':
launchApp
  Code: function(age = c("Age00_04", "Age05_14", "Age15_19",
                 "Age20_24", "Age25_34", "Age35_44", "Age45_54",
                 "Age55_64", "Age65_74", "Age75_84", "Age85plus"),
                 religion = c("Christianity", "Catholic", "Buddhism",
                 "Islam", "Judaism", "NoReligion"), other =
                 c("Population", "MedianIncome", "Unemployed",
                 "Bachelor", "Postgraduate", "BornOverseas",
                 "Indigenous", "EnglishOnly", "OtherLanguageHome",
                 "Married", "DeFacto", "FamilyRatio", "Internet",
                 "NotOwned"), palette = c("#1B9E77", "#F0027F",
                 "#E6AB02", "#66A61E", "#7570B3", "#D95F02",
                 "#3690C0"))
  Docs: function(age = c("Age00_04", "Age05_14", "Age15_19",
                 "Age20_24", "Age25_34", "Age35_44", "Age45_54",
                 "Age55_64", "Age65_74", "Age75_84", "Age85plus"),
                 religion = c("Christianity", "Catholic", "Buddhism",
                 "Islam", "Judaism", "NoReligion"), other =
                 c("Population", "MedianIncome", "Unemployed",
                 "Bachelor", "Postgraduate", "BornOverseas",
                 "Indigenous", "EnglishOnly", "OtherLanguageHome",
                 "Married", "DeFacto", "FamilyRatio", "Internet",
                 "NotOwned"), palette = c(forest = "#1b9e77", pink =
                 "#f0027f", yellow = "#e6ab02", green = "#66a61e",
                 violet = "#7570b3", orange = "#d95f02", blue =
                 "#3690c0"))
  Mismatches in argument default values:
    Name: 'palette'
    Code: c("#1B9E77", "#F0027F", "#E6AB02", "#66A61E", "#7570B3", "#D95F02", 
          "#3690C0")
    Docs: c(forest = "#1b9e77", pink = "#f0027f", yellow = "#e6ab02", green = "#66a61e", 
          violet = "#7570b3", orange = "#d95f02", blue = "#3690c0")

* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... [2s] OK
** running examples for arch 'x64' ... [3s] OK
* checking PDF version of manual ... OK
* DONE
Status: 1 WARNING, 2 NOTEs
```

**Comment by sckott** [comment]
a similar issue from jim hester https://github.com/hadley/devtools/issues/587

**Comment by sckott** [comment]
hmm, shouldn't `GGally` and `corrplot` be in Suggests or Enhances if used in vignettes?

**Comment by benmarwick** [comment]
@cpsievert  has updated the description in https://github.com/ropenscilabs/eechidna/commit/1cf65c747b3ec7f8b339d818bfade049f58a1cdf 

I think it might be time for @hadley to get his [postcards](https://twitter.com/hadleywickham/status/346809866532306945) ready... We've used devtools, and about to make a CRAN maintainer grumpy with this incurable note....

**Comment by sckott** [comment]
sorry couldn't help more, part of problem is i still use plain ol knitr for vignettes, need to start using rmarkdown vign.

**Comment by dicook** [comment]
Ben,

I just used devtools to check and didn’t get any errors, warnings or notes. Are you still having trouble?

cheers,
Di

> library(devtools)
> build()
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
>   --no-save --no-restore --quiet CMD build '/Users/dicook/Rpackages/eechidna'  \
>   --no-resave-data --no-manual 
- checking for file ‘/Users/dicook/Rpackages/eechidna/DESCRIPTION’ ... OK
- preparing ‘eechidna’:
- checking DESCRIPTION meta-information ... OK
- checking for LF line-endings in source and make files
- checking for empty or unneeded directories
- looking to see if a ‘data/datalist’ file should be added
- building ‘eechidna_0.1.tar.gz’

[1] "/Users/dicook/Rpackages/eechidna_0.1.tar.gz"

> check()
> Updating eechidna documentation
> Loading eechidna
> Setting env vars ---------------------------------------------------------------
> CFLAGS  : -Wall -pedantic
> CXXFLAGS: -Wall -pedantic
> Building eechidna --------------------------------------------------------------
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
>   --no-save --no-restore --quiet CMD build '/Users/dicook/Rpackages/eechidna'  \
>   --no-resave-data --no-manual 
- checking for file ‘/Users/dicook/Rpackages/eechidna/DESCRIPTION’ ... OK
- preparing ‘eechidna’:
- checking DESCRIPTION meta-information ... OK
- checking for LF line-endings in source and make files
- checking for empty or unneeded directories
- looking to see if a ‘data/datalist’ file should be added
- building ‘eechidna_0.1.tar.gz’

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking eechidna --------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD check  \
  '/var/folders/9d/njpjyby920z_l16gb_p5wx0c0000gn/T//RtmpytzMAf/eechidna_0.1.tar.gz'  \
  --as-cran --timings --no-manual 
- using log directory ‘/private/var/folders/9d/njpjyby920z_l16gb_p5wx0c0000gn/T/RtmpytzMAf/eechidna.Rcheck’
- using R version 3.3.0 (2016-05-03)
- using platform: x86_64-apple-darwin13.4.0 (64-bit)
- using session charset: UTF-8
- using options ‘--no-manual --as-cran’
- checking for file ‘eechidna/DESCRIPTION’ ... OK
- this is package ‘eechidna’ version ‘0.1’
- checking package namespace information ... OK
- checking package dependencies ... OK
- checking if this is a source package ... OK
- checking if there is a namespace ... OK
- checking for executable files ... OK
- checking for hidden files and directories ... OK
- checking for portable file names ... OK
- checking for sufficient/correct file permissions ... OK
- checking whether package ‘eechidna’ can be installed ... OK
- checking installed package size ... OK
- checking package directory ... OK
- checking DESCRIPTION meta-information ... OK
- checking top-level files ... OK
- checking for left-over files ... OK
- checking index information ... OK
- checking package subdirectories ... OK
- checking R files for non-ASCII characters ... OK
- checking R files for syntax errors ... OK
- checking whether the package can be loaded ... OK
- checking whether the package can be loaded with stated dependencies ... OK
- checking whether the package can be unloaded cleanly ... OK
- checking whether the namespace can be loaded with stated dependencies ... OK
- checking whether the namespace can be unloaded cleanly ... OK
- checking dependencies in R code ... OK
- checking S3 generic/method consistency ... OK
- checking replacement functions ... OK
- checking foreign function calls ... OK
- checking R code for possible problems ... OK
- checking Rd files ... OK
- checking Rd metadata ... OK
- checking Rd line widths ... OK
- checking Rd cross-references ... OK
- checking for missing documentation entries ... OK
- checking for code/documentation mismatches ... OK
- checking Rd \usage sections ... OK
- checking Rd contents ... OK
- checking for unstated dependencies in examples ... OK
- checking contents of ‘data’ directory ... OK
- checking data for non-ASCII characters ... OK
- checking data for ASCII and uncompressed saves ... OK
- checking files in ‘vignettes’ ... OK
- checking examples ... OK
- DONE

Status: OK

R CMD check results
0 errors | 0 warnings | 0 notes

> On May 19, 2016, at 4:45 PM, Ben Marwick notifications@github.com wrote:
> 
> No change when using knitr::knitr in the vignette header... @cpsievert we have some new Codoc mismatches from your recent changes...
> - using log directory 'd:/RCompile/CRANguest/R-devel/eechidna.Rcheck'
> - using R Under development (unstable) (2016-05-18 r70631)
> - using platform: x86_64-w64-mingw32 (64-bit)
> - using session charset: ISO8859-1
> - checking for file 'eechidna/DESCRIPTION' ... OK
> - this is package 'eechidna' version '0.1'
> - checking CRAN incoming feasibility ... NOTE
>   Maintainer: 'Ben Marwick benmarwick@gmail.com'
> 
> New submission
> 
> Package has a VignetteBuilder field but no prebuilt vignette index.
> - checking package namespace information ... OK
> - checking package dependencies ... OK
> - checking if this is a source package ... OK
> - checking if there is a namespace ... OK
> - checking for hidden files and directories ... OK
> - checking for portable file names ... OK
> - checking whether package 'eechidna' can be installed ... OK
> - checking installed package size ... OK
> - checking package directory ... OK
> - checking DESCRIPTION meta-information ... OK
> - checking top-level files ... NOTE
>   Non-standard file/directory found at top level:
>   'README.html'
> - checking for left-over files ... OK
> - checking index information ... OK
> - checking package subdirectories ... OK
> - checking R files for non-ASCII characters ... OK
> - checking R files for syntax errors ... OK
> - loading checks for arch 'i386'
>   *\* checking whether the package can be loaded ... OK
>   *\* checking whether the package can be loaded with stated dependencies ... OK
>   *\* checking whether the package can be unloaded cleanly ... OK
>   *\* checking whether the namespace can be loaded with stated dependencies ... OK
>   *\* checking whether the namespace can be unloaded cleanly ... OK
>   *\* checking loading without being on the library search path ... OK
>   *\* checking use of S3 registration ... OK
> - loading checks for arch 'x64'
>   *\* checking whether the package can be loaded ... OK
>   *\* checking whether the package can be loaded with stated dependencies ... OK
>   *\* checking whether the package can be unloaded cleanly ... OK
>   *\* checking whether the namespace can be loaded with stated dependencies ... OK
>   *\* checking whether the namespace can be unloaded cleanly ... OK
>   *\* checking loading without being on the library search path ... OK
>   *\* checking use of S3 registration ... OK
> - checking dependencies in R code ... OK
> - checking S3 generic/method consistency ... OK
> - checking replacement functions ... OK
> - checking foreign function calls ... OK
> - checking R code for possible problems ... OK
> - checking Rd files ... OK
> - checking Rd metadata ... OK
> - checking Rd line widths ... OK
> - checking Rd cross-references ... OK
> - checking for missing documentation entries ... OK
> - checking for code/documentation mismatches ... WARNING
>   Codoc mismatches from documentation object 'launchApp':
>   launchApp
>   Code: function(age = c("Age00_04", "Age05_14", "Age15_19",
>                  "Age20_24", "Age25_34", "Age35_44", "Age45_54",
>                  "Age55_64", "Age65_74", "Age75_84", "Age85plus"),
>                  religion = c("Christianity", "Catholic", "Buddhism",
>                  "Islam", "Judaism", "NoReligion"), other =
>                  c("Population", "MedianIncome", "Unemployed",
>                  "Bachelor", "Postgraduate", "BornOverseas",
>                  "Indigenous", "EnglishOnly", "OtherLanguageHome",
>                  "Married", "DeFacto", "FamilyRatio", "Internet",
>                  "NotOwned"), palette = c("#1B9E77", "#F0027F",
>                  "#E6AB02", "#66A61E", "#7570B3", "#D95F02",
>                  "#3690C0"))
>   Docs: function(age = c("Age00_04", "Age05_14", "Age15_19",
>                  "Age20_24", "Age25_34", "Age35_44", "Age45_54",
>                  "Age55_64", "Age65_74", "Age75_84", "Age85plus"),
>                  religion = c("Christianity", "Catholic", "Buddhism",
>                  "Islam", "Judaism", "NoReligion"), other =
>                  c("Population", "MedianIncome", "Unemployed",
>                  "Bachelor", "Postgraduate", "BornOverseas",
>                  "Indigenous", "EnglishOnly", "OtherLanguageHome",
>                  "Married", "DeFacto", "FamilyRatio", "Internet",
>                  "NotOwned"), palette = c(forest = "#1b9e77", pink =
>                  "#f0027f", yellow = "#e6ab02", green = "#66a61e",
>                  violet = "#7570b3", orange = "#d95f02", blue =
>                  "#3690c0"))
>   Mismatches in argument default values:
>     Name: 'palette'
>     Code: c("#1B9E77", "#F0027F", "#E6AB02", "#66A61E", "#7570B3", "#D95F02", 
>           "#3690C0")
>     Docs: c(forest = "#1b9e77", pink = "#f0027f", yellow = "#e6ab02", green = "#66a61e", 
>           violet = "#7570b3", orange = "#d95f02", blue = "#3690c0")
> - checking Rd \usage sections ... OK
> - checking Rd contents ... OK
> - checking for unstated dependencies in examples ... OK
> - checking contents of 'data' directory ... OK
> - checking data for non-ASCII characters ... OK
> - checking data for ASCII and uncompressed saves ... OK
> - checking files in 'vignettes' ... OK
> - checking examples ...
>   *\* running examples for arch 'i386' ... [2s] OK
>   *\* running examples for arch 'x64' ... [3s] OK
> - checking PDF version of manual ... OK
> - DONE
>   Status: 1 WARNING, 2 NOTEs
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub

---

Di Cook
visnut@gmail.com

**Comment by benmarwick** [comment]
Right, I get the same. The problem with the vignettes is only evident when I do devtools::build_win() which builds on the dev version of R.

Get Outlook for Androidhttps://aka.ms/ghei36

On Fri, May 20, 2016 at 3:23 PM -0700, "Dianne Cook" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ben,

I just used devtools to check and didn’t get any errors, warnings or notes. Are you still having trouble?

cheers,
Di

> library(devtools)
> build()
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ \
> --no-save --no-restore --quiet CMD build '/Users/dicook/Rpackages/eechidna' \
> --no-resave-data --no-manual
- checking for file ‘/Users/dicook/Rpackages/eechidna/DESCRIPTION’ ... OK
- preparing ‘eechidna’:
- checking DESCRIPTION meta-information ... OK
- checking for LF line-endings in source and make files
- checking for empty or unneeded directories
- looking to see if a ‘data/datalist’ file should be added
- building ‘eechidna_0.1.tar.gz’

[1] "/Users/dicook/Rpackages/eechidna_0.1.tar.gz"

> check()
> Updating eechidna documentation
> Loading eechidna
> Setting env vars ---------------------------------------------------------------
> CFLAGS : -Wall -pedantic
> CXXFLAGS: -Wall -pedantic
> Building eechidna --------------------------------------------------------------
> '/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ \
> --no-save --no-restore --quiet CMD build '/Users/dicook/Rpackages/eechidna' \
> --no-resave-data --no-manual
- checking for file ‘/Users/dicook/Rpackages/eechidna/DESCRIPTION’ ... OK
- preparing ‘eechidna’:
- checking DESCRIPTION meta-information ... OK
- checking for LF line-endings in source and make files
- checking for empty or unneeded directories
- looking to see if a ‘data/datalist’ file should be added
- building ‘eechidna_0.1.tar.gz’

Setting env vars ---------------------------------------------------------------
_R_CHECK_CRAN_INCOMING_ : FALSE
_R_CHECK_FORCE_SUGGESTS_: FALSE
Checking eechidna --------------------------------------------------------------
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ \
--no-save --no-restore --quiet CMD check \
'/var/folders/9d/njpjyby920z_l16gb_p5wx0c0000gn/T//RtmpytzMAf/eechidna_0.1.tar.gz' \
--as-cran --timings --no-manual
- using log directory ‘/private/var/folders/9d/njpjyby920z_l16gb_p5wx0c0000gn/T/RtmpytzMAf/eechidna.Rcheck’
- using R version 3.3.0 (2016-05-03)
- using platform: x86_64-apple-darwin13.4.0 (64-bit)
- using session charset: UTF-8
- using options ‘--no-manual --as-cran’
- checking for file ‘eechidna/DESCRIPTION’ ... OK
- this is package ‘eechidna’ version ‘0.1’
- checking package namespace information ... OK
- checking package dependencies ... OK
- checking if this is a source package ... OK
- checking if there is a namespace ... OK
- checking for executable files ... OK
- checking for hidden files and directories ... OK
- checking for portable file names ... OK
- checking for sufficient/correct file permissions ... OK
- checking whether package ‘eechidna’ can be installed ... OK
- checking installed package size ... OK
- checking package directory ... OK
- checking DESCRIPTION meta-information ... OK
- checking top-level files ... OK
- checking for left-over files ... OK
- checking index information ... OK
- checking package subdirectories ... OK
- checking R files for non-ASCII characters ... OK
- checking R files for syntax errors ... OK
- checking whether the package can be loaded ... OK
- checking whether the package can be loaded with stated dependencies ... OK
- checking whether the package can be unloaded cleanly ... OK
- checking whether the namespace can be loaded with stated dependencies ... OK
- checking whether the namespace can be unloaded cleanly ... OK
- checking dependencies in R code ... OK
- checking S3 generic/method consistency ... OK
- checking replacement functions ... OK
- checking foreign function calls ... OK
- checking R code for possible problems ... OK
- checking Rd files ... OK
- checking Rd metadata ... OK
- checking Rd line widths ... OK
- checking Rd cross-references ... OK
- checking for missing documentation entries ... OK
- checking for code/documentation mismatches ... OK
- checking Rd \usage sections ... OK
- checking Rd contents ... OK
- checking for unstated dependencies in examples ... OK
- checking contents of ‘data’ directory ... OK
- checking data for non-ASCII characters ... OK
- checking data for ASCII and uncompressed saves ... OK
- checking files in ‘vignettes’ ... OK
- checking examples ... OK
- DONE

Status: OK

R CMD check results
0 errors | 0 warnings | 0 notes

> On May 19, 2016, at 4:45 PM, Ben Marwick notifications@github.com wrote:
> 
> No change when using knitr::knitr in the vignette header... @cpsievert we have some new Codoc mismatches from your recent changes...
> - using log directory 'd:/RCompile/CRANguest/R-devel/eechidna.Rcheck'
> - using R Under development (unstable) (2016-05-18 r70631)
> - using platform: x86_64-w64-mingw32 (64-bit)
> - using session charset: ISO8859-1
> - checking for file 'eechidna/DESCRIPTION' ... OK
> - this is package 'eechidna' version '0.1'
> - checking CRAN incoming feasibility ... NOTE
>   Maintainer: 'Ben Marwick benmarwick@gmail.com'
> 
> New submission
> 
> Package has a VignetteBuilder field but no prebuilt vignette index.
> - checking package namespace information ... OK
> - checking package dependencies ... OK
> - checking if this is a source package ... OK
> - checking if there is a namespace ... OK
> - checking for hidden files and directories ... OK
> - checking for portable file names ... OK
> - checking whether package 'eechidna' can be installed ... OK
> - checking installed package size ... OK
> - checking package directory ... OK
> - checking DESCRIPTION meta-information ... OK
> - checking top-level files ... NOTE
>   Non-standard file/directory found at top level:
>   'README.html'
> - checking for left-over files ... OK
> - checking index information ... OK
> - checking package subdirectories ... OK
> - checking R files for non-ASCII characters ... OK
> - checking R files for syntax errors ... OK
> - loading checks for arch 'i386'
>   *\* checking whether the package can be loaded ... OK
>   *\* checking whether the package can be loaded with stated dependencies ... OK
>   *\* checking whether the package can be unloaded cleanly ... OK
>   *\* checking whether the namespace can be loaded with stated dependencies ... OK
>   *\* checking whether the namespace can be unloaded cleanly ... OK
>   *\* checking loading without being on the library search path ... OK
>   *\* checking use of S3 registration ... OK
> - loading checks for arch 'x64'
>   *\* checking whether the package can be loaded ... OK
>   *\* checking whether the package can be loaded with stated dependencies ... OK
>   *\* checking whether the package can be unloaded cleanly ... OK
>   *\* checking whether the namespace can be loaded with stated dependencies ... OK
>   *\* checking whether the namespace can be unloaded cleanly ... OK
>   *\* checking loading without being on the library search path ... OK
>   *\* checking use of S3 registration ... OK
> - checking dependencies in R code ... OK
> - checking S3 generic/method consistency ... OK
> - checking replacement functions ... OK
> - checking foreign function calls ... OK
> - checking R code for possible problems ... OK
> - checking Rd files ... OK
> - checking Rd metadata ... OK
> - checking Rd line widths ... OK
> - checking Rd cross-references ... OK
> - checking for missing documentation entries ... OK
> - checking for code/documentation mismatches ... WARNING
>   Codoc mismatches from documentation object 'launchApp':
>   launchApp
>   Code: function(age = c("Age00_04", "Age05_14", "Age15_19",
>   "Age20_24", "Age25_34", "Age35_44", "Age45_54",
>   "Age55_64", "Age65_74", "Age75_84", "Age85plus"),
>   religion = c("Christianity", "Catholic", "Buddhism",
>   "Islam", "Judaism", "NoReligion"), other =
>   c("Population", "MedianIncome", "Unemployed",
>   "Bachelor", "Postgraduate", "BornOverseas",
>   "Indigenous", "EnglishOnly", "OtherLanguageHome",
>   "Married", "DeFacto", "FamilyRatio", "Internet",
>   "NotOwned"), palette = c("#1B9E77", "#F0027F",
>   "#E6AB02", "#66A61E", "#7570B3", "#D95F02",
>   "#3690C0"))
>   Docs: function(age = c("Age00_04", "Age05_14", "Age15_19",
>   "Age20_24", "Age25_34", "Age35_44", "Age45_54",
>   "Age55_64", "Age65_74", "Age75_84", "Age85plus"),
>   religion = c("Christianity", "Catholic", "Buddhism",
>   "Islam", "Judaism", "NoReligion"), other =
>   c("Population", "MedianIncome", "Unemployed",
>   "Bachelor", "Postgraduate", "BornOverseas",
>   "Indigenous", "EnglishOnly", "OtherLanguageHome",
>   "Married", "DeFacto", "FamilyRatio", "Internet",
>   "NotOwned"), palette = c(forest = "#1b9e77", pink =
>   "#f0027f", yellow = "#e6ab02", green = "#66a61e",
>   violet = "#7570b3", orange = "#d95f02", blue =
>   "#3690c0"))
>   Mismatches in argument default values:
>   Name: 'palette'
>   Code: c("#1B9E77", "#F0027F", "#E6AB02", "#66A61E", "#7570B3", "#D95F02",
>   "#3690C0")
>   Docs: c(forest = "#1b9e77", pink = "#f0027f", yellow = "#e6ab02", green = "#66a61e",
>   violet = "#7570b3", orange = "#d95f02", blue = "#3690c0")
> - checking Rd \usage sections ... OK
> - checking Rd contents ... OK
> - checking for unstated dependencies in examples ... OK
> - checking contents of 'data' directory ... OK
> - checking data for non-ASCII characters ... OK
> - checking data for ASCII and uncompressed saves ... OK
> - checking files in 'vignettes' ... OK
> - checking examples ...
>   *\* running examples for arch 'i386' ... [2s] OK
>   *\* running examples for arch 'x64' ... [3s] OK
> - checking PDF version of manual ... OK
> - DONE
>   Status: 1 WARNING, 2 NOTEs
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub

---

Di Cook
visnut@gmail.com

**Comment by benmarwick** [comment]
results of `devtools::build_win()` are now all good, using 727a524dd964e862b68ab409143f43a2ce0dd890

It seems like all the vignettes are knitted in a single common R environment, which was unexpected. 

I was getting an error in one vignette, and poking around in the dark for a solution I added library(plyr) at the top of all the other vignettes, and that solved it.

```
* using log directory 'd:/RCompile/CRANguest/R-release/eechidna.Rcheck'
* using R version 3.3.0 (2016-05-03)
* using platform: x86_64-w64-mingw32 (64-bit)
* using session charset: ISO8859-1
* checking for file 'eechidna/DESCRIPTION' ... OK
* this is package 'eechidna' version '0.1'
* checking CRAN incoming feasibility ... NOTE
Maintainer: 'Ben Marwick <benmarwick@gmail.com>'

New submission
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking whether package 'eechidna' can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking 'build' directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... OK
** checking whether the namespace can be unloaded cleanly ... OK
** checking loading without being on the library search path ... OK
** checking use of S3 registration ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd line widths ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of 'data' directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking installed files from 'inst/doc' ... OK
* checking files in 'vignettes' ... OK
* checking examples ...
** running examples for arch 'i386' ... [2s] OK
** running examples for arch 'x64' ... [2s] OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in 'inst/doc' ... OK
* checking re-building of vignette outputs ... [24s] OK
* checking PDF version of manual ... OK
* DONE
Status: 1 NOTE

```

**Comment by benmarwick** [comment]
I've submitted it to CRAN now, let's see how they like it!

![clipboard01](https://cloud.githubusercontent.com/assets/1262179/15455143/bc862830-208e-11e6-8dd5-2953be7a9aa8.png)

**Comment by benmarwick** [comment]
Feedback on the CRAN submission:

two issues:
1. Please do not wrap all examples in \dontrun{}, we'd like to see some examples run by R CMD check so that your example code gets executed, if it does not take more than 5 sec for each Rd file.
2. Please mention all authors and copyright holder (incl., e.g., Commonwealth of Australia) with an appropriate role in Authors@R (and then you can omit Author field that is auto-generated from Authors@R during R CMD build automatically.

Best,
Uwe Ligges

Also, this is too huge:

Size of tarball: 28698012 bytes is > 5MB (max size for a CRAN package)-

Best,
Uwe Ligges

**Comment by benmarwick** [comment]
I've dealt with all of these, and 21cd19ba6cfab39df6162bf67920878575c78ff3 has gone to CRAN for a 2nd attempt.

**Comment by benmarwick** [comment]
And our package is on CRAN! 

Here it is: https://cran.r-project.org/web/packages/eechidna/index.html

> Date: Mon, 23 May 2016 06:01:59 +0200
> From: Kurt Hornik Kurt.Hornik@..
> To: Ben Marwick benmarwick@..
> Cc: CRAN cran@r-project.org
> Subject: Re: CRAN submission eechidna 0.1
> Reply-To: Kurt.Hornik@...
> 
> > > > > > Ben Marwick writes:
> 
> Thanks, on CRAN now.
> 
> Best
> -k
