### ISSUE TITLE
use NEWS, git tags, and releases

### ISSUE THREAD

**Issue by sckott** [ropenscilabs/eechidna#8]
hey @benmarwick - We want all rOpenSci pkgs to consistently keep track of changes, following https://github.com/ropensci/onboarding/blob/master/packaging_guide.md#-news  
- use a `NEWS` or `NEWS.md` file to keep track of changes with each version released to CRAN
- git tag each CRAN version
- use the [releases tab](https://github.com/ropenscilabs/eechidna/releases) on this repo to include the associated NEWS items for each tag/version

Can you please do the three above items from now on?

**Comment by benmarwick** [comment]
Thanks, yes, no problem, all done.
- [x] use a NEWS or NEWS.md file to keep track of changes with each version released to CRAN
- [x] git tag each CRAN version
- [x] use the releases tab on this repo to include the associated NEWS items for each tag/version
