### ISSUE TITLE
rmapshaper now on CRAN

### ISSUE THREAD

**Issue by ateucher** [ropenscilabs/eechidna#9]
@benmarwick Asked me to let you folks know when rmapshaper landed on CRAN. It was accepted and released this morning with version 0.1.0. Thanks for the nudge along, otherwise I probably wouldn't have done it by this point. :)

**Comment by benmarwick** [comment]
Hi Andy, Congratulations on achieving CRAN! And thanks for the update. I'll make some edits to this to reflect this change.

**Comment by benmarwick** [comment]
Noted this in https://github.com/ropenscilabs/eechidna/commit/2a9dad5176f095cf2fe0f5378b4fc428314bdb57 (sorry to take so long!)
